entity/machine.go
entity/volume_group.go
test/testdata/maas/machine.json

When a machine is provisioned with LVM storage, an error is thrown:
```machine_test.go:15: json: cannot unmarshal object into Go struct field Machine.volume_groups of type string```
This is because `volume_groups` isn't an array of strings, it's an array of objects accroding to https://maas.io/docs/api
This PR adds a VolumeGroup type, and adds a `volume_group` array to the tests.

Fix marshalling error when a machine has LVM volume groups

---

entity/machine.go

Allocate op doesn't support enable_hw_sync, according to https://maas.io/docs/api

fix: remove enable_hw_sync from allocate

---

entity/machine.go
entity/machine_test.go

This is a follow up for https://github.com/maas/gomaasclient/pull/9
It seems to be a good idea exposing information whether hardware sync is enabled for the machine or not.
This functionality is available in MAAS 3.2+ but `enable_hw_sync` property was never exposed over API. However for machine with enabled hardware sync API returns `last_sync`, `sync_interval` and `next_sync` properties that can be used to deduce if hardware sync is enabled or not.
This PR adds proper JSON unmarshal for `enable_hw_sync` once this [MP](https://code.launchpad.net/~troyanov/maas/+git/maas/+merge/442692) will be merged, and in other scenarios it will deduce it from already available proeprties.

feat: expose hardware sync info

---

api/machines.go
client/machines.go

Expose op-accept_all call via api in order to provide ability for newly discovered machines

Support op-accept_all API call

---

go.mod
go.sum

Bumping gomaasapi to v2.1.0 to include https://bugs.launchpad.net/maas/+bug/2034014

bump gomaasapi to v2.1.0

---

api/machine.go
api/machines.go
client/machine.go
client/machines.go
client/utils.go
client/utils_test.go

Update power parameters to be `map[string]interface{}` instead of `map[string]string` to cover all type of parameters.
Being more specific, power parameters can also contain a key to `[]string` as it is happening with [IPMI](https://maas.io/docs/api#ipmi-ipmi) `workaround_flags`. This PR makes sure that a machine with IPMI can also be created/updated and that its power parameters can be fetched without an issue.

Fix parsing of power parameters

---

api/network_interface.go
client/network_interface.go
entity/network_interface.go
entity/network_interface_test.go

This PR includes the following:
- Update network interface fields which are different from the create/update parameters
- Introduce `NetworkInterfaceDiscoveredIP ` struct to represent `discovered` nested field of a network interface
- Update create parameters for each of the types physical, vlan, bridge, bond with proper fields and inheritance
- Introduce update parameters which can support the common interface update endpoint

Fix network parameters

---

entity/block_device.go
entity/block_device_partition.go
entity/machine.go
entity/vm_host.go
entity/volume_group.go

Use `int64` type for disk size.
Resolves https://github.com/maas/terraform-provider-maas/issues/116
When compiled on a 32-bit platform `int` will be `int32` and will lead to an overflow and JSON unmarshal error:
```go
type Foo struct {
Size int32
}
func main() {
data := []byte(`{"Size": 128032178176}`)
foo := Foo{}
err := json.Unmarshal(data, &foo)
if err != nil {
fmt.Println(err)
}
fmt.Println(foo.Size)
}
```

fix: unmarshal number leads to int overflow

---

api/machine.go
client/machine.go
entity/machine.go

This PR adds the option to release a single machine through the `gomaasclient` so as to enable erase disk functionality which is currently missing from the Terraform provider

Add release machine operation

---

entity/machine.go

as per API documentation the release params needs to boolean However, currently it is being used as string

Fix params for release api

---

api/machine.go
client/machine.go
entity/machine.go

Added support for Machine Power On/Off operations

feat: add machine Power On/Off Operations

---

client/vm_host.go
entity/vm_host.go

This PR includes:
- Addition of `key`, `certificate` parameters to add LXD hosts with existing credentials
- Consumption of the VM host refresh result data

feat: add power parameters for LXD hosts

---

api/maas_server.go
client/client.go
client/maas_server.go

This PR includes the following:
- Update the initial interface signature so that Get can return a byte slice. This is needed since get can return a mixture of int, string or boolean values
- Implement the existing API
- Expose the API interaction through the client
**NOTE:** It is user responsibility to unmarshal the returned value to an appropriate type.

feat: add MAAS server API endpoint interactions

---

api/device.go
api/machine.go
client/device.go
client/machine.go
entity/device.go
entity/machine.go

add, remove or update Machine/Device workload annotations

feat: support for adding, removing, updating machines/devices Workload Annotations

---

api/boot_resource.go
api/boot_resources.go
api/boot_source.go
api/boot_source_selection.go
api/boot_source_selections.go
api/boot_sources.go
client/boot_resource.go
client/boot_resources.go
client/boot_source.go
client/boot_source_selection.go
client/boot_source_selections.go
client/boot_sources.go
client/client.go
entity/boot_resource.go
entity/boot_source.go
entity/boot_source_selection.go

Include the following boot entities:
- Boot sources
- Boot source selections
- Boot resources
NOTE: Creation of a custom boot resource has not been implemented as it requires special handling with file contents, which is different than the underlying `gomaasapi` implementation [CallPostFiles](https://github.com/juju/gomaasapi/blob/master/maasobject.go#L190).

feat: add boot related entities and API endpoint interactions

---

api/machine.go
client/machine.go
entity/machine.go
go.mod
go.sum

Add endpoint for machine details that is fetching the bson response and unmarshal it before returning the data to the user.
**NOTE:** Both lldp and lshw are valid XML but intentionally their unmarshaling is not performed so that user can parse them as desired.

feat: add machine details API endpoint interaction

---

client/client.go

This pull adds a new constructor function that takes in an `http.Transport`. This would allow users to pass in instrumented transports to support observability efforts and trace API requests to the MAAS backend.
I think a move towards a builder / option pattern would be more elegant here but I'm keeping my changes minimal. 
Fixes https://github.com/maas/gomaasclient/issues/32

Add constructor with pluggable transport

---

entity/machine.go

`"bios_boot_method"` info related to machine was missing

fix: add missing field for machine object

---

api/discoveries.go
api/discovery.go
client/discoveries.go
client/discovery.go
entity/discovery.go

Add Listing API interaction for node device discovery

feat: Add node device discovery API endpoint interaction

---

api/machines.go
client/machines.go
entity/machine.go

This PR contains all the filter options that can be set to MAAS v2 API to limit the machine list results.
The full list was gathered from source code:
- https://github.com/canonical/maas/blob/master/src/maasserver/api/machines.py#L1962
- https://github.com/canonical/maas/blob/master/src/maasserver/api/nodes.py#L807
- https://github.com/canonical/maas/blob/master/src/maasserver/node_constraint_filter_forms.py#L1356
- https://github.com/canonical/maas/blob/master/src/maasserver/node_constraint_filter_forms.py#L729
Fixes: #67

fix: machines get should accept query params

---

api/machine.go
client/machine.go
go.mod

Add support for machine API call `op-get_curtin_config`. This endpoint returns the curtin config in YAML format.

feat: add machine method get-curtin-config

---

api/rack_controller.go
api/rack_controllers.go
client/client.go
client/rack_contoller.go
client/rack_controllers.go
entity/machine.go
entity/node.go
entity/rack_controller.go
entity/rack_controller_test.go
entity/subnet.go
test/testdata/maas/rack_controller.json
test/testdata/maas/rack_controllers.json

This PR includes the following changes:
- Update Rack controller entities which were incomplete and not used
- Add interactions with Rack controller(s) endpoints
- Move node logic from machine to node and let machines and rack controllers inherit them
- Update rack controller sample JSON responses, used for tests
- Update of `Subnet` entity to include missing fields. This is needed to have successful rack controller tests. The tests are failing if the Go structs do not contain fields found in the response. Subnet is indirect as `Rack Controller` -> `Interfaces` -> `Links` -> `Subnets`
- Add some missing fields to machines
- Fix a typo in one of rack controller test names

feat: support rack controllers

---

README.md

It seems as part of 608640d1 the signature of Machines.Get changed breaking the example in the README.md. This change fixes the example.

Fix Machines.Get example in README

---

entity/machine.go

This will allow the option to "deploy in memory"  Please let me know if anything else is needed.

feat: add EphemeralDeploy to the Machine and MachineDeployParams

---

api/dns_resource_records.go
api/dns_resources.go
client/dns_resource_records.go
client/dns_resources.go
entity/dns_resource.go
entity/dns_resource_record.go

- Updating the `DNSResources` and `DNSResourceRecords` Get() apis to accept query params as specified in the [API docs](https://maas.io/docs/api).
Resolves GH: #89

fix: add ability to pass query params to Get() dns resources and records

---

entity/machine.go

- Rename `PXEMacAddress` to `MACAddresses` and convert from `string` to `[]string`
- Align struct fields after the change
Resolves GH: #83

fix: allow requesting multiple MACs for machines

---

api/volume_group.go
api/volume_groups.go
client/client.go
client/volume_group.go
client/volume_groups.go
entity/volume_group.go
entity/volume_group_test.go
test/testdata/maas/volume_group.json
test/testdata/maas/volume_groups.json

This PR adds the support of following MAAS API endpoint.
- `DELETE /MAAS/api/2.0/nodes/{system_id}/volume-group/{id}/`: Delete volume group
- `GET /MAAS/api/2.0/nodes/{system_id}/volume-group/{id}/`: Read a volume group
- `PUT /MAAS/api/2.0/nodes/{system_id}/volume-group/{id}/`: Update a volume group
- `POST /MAAS/api/2.0/nodes/{system_id}/volume-group/{id}/op-create_logical_volume`: Create a logical volume
- `POST /MAAS/api/2.0/nodes/{system_id}/volume-group/{id}/op-delete_logical_volume`: Delete a logical volume
- `GET /MAAS/api/2.0/nodes/{system_id}/volume-groups/`: List all volume groups
- `POST /MAAS/api/2.0/nodes/{system_id}/volume-groups/`: Create a volume group
I think this change would resolve #86.

feat: add volume group API endpoint interaction

---

entity/machine.go

- Turn the VMHost machine field to a pointer to differentiate machines backed by a VM host (VMs) and physical machines.
- Declare an internal `MachineVMHost` since only 3 fields of the machine's VM host are included in the response of the API [link](https://github.com/canonical/maas/blob/master/src/maasserver/api/machines.py#L449)
Resolves: #27

fix: make machine VMHost pointer

---

client/boot_resources.go

https://maas.io/docs/api shows the operations use the format `op-snake_case_operation`, which can be verified with your lcoal MAAS:
http://$ip:5240/MAAS/api/2.0/boot-resources/op-is-importing fails, while http://$ip:5240/MAAS/api/2.0/boot-resources/op-is_importing succeeds

fix: use snake_case for import operations

---

entity/vlan.go

- allow empty primary/secondary rack controller to be set to form data
- convert relay_vlan to `*string` as the only way to unset it in MAAS is to provide an empty string 
- field align the fields after the change
Resolves: #117

fix: properly handle VLAN DHCP options

---

entity/boot_resource.go
entity/boot_resource_test.go
test/testdata/maas/boot_resource.json
test/testdata/maas/boot_resources.json

The API v2 can optionally include `base_image`, `title` attributes on boot resources. Update gomaasclient to include these fields.
Resolves: #120

fix: include missing fields on boot-resources objects

---

entity/volume_group.go

Fixes a typo in `Size` field of `LogicalVolumeParams` struct so that it is `url` instead of `json`.
```go
logicalVolume, err := client.VolumeGroup.CreateLogicalVolume(machines[0].SystemID, volumeGroup.ID, &entity.LogicalVolumeParams{
Name: "lvroot",
Size: 10 * 1024 * 1024 * 1024,
})
if err != nil {
fmt.Println(err)
}
fmt.Println(logicalVolume.Name)
fmt.Println(logicalVolume.AvailableSize)
```
```bash
$ go run main.go 
vgroot-lvroot
48301604864
```
```bash
$ go run main.go 
vgroot-lvroot
10729029632
```
Resolves: #123

fix: expect url instead of json for Size in LogicalVolumeParams

---

DEVELOPMENT.md
entity/vm_host.go

Adds missing params for vm-host
Enables: https://github.com/canonical/terraform-provider-maas/pull/314

feat: add-missing-params-for-to-vm-host

---

entity/raid.go

The `size` field in RAID struct returns a `float64` rather than `int64`
*A clear and concise description of your changes here.*
Resolves #126 
When RAID-10 is selected, the `size` field returns a float, rather than an int due to a bug in MAAS. 
*A link to an issue or ticket that this PR is addressing.*

fix: RAID returns float not int in some cases

---

entity/node_script.go

- Convert `Packages`, `Results`, `Parameters` to `json.RawMessage` so that they can be Marshalled later on
- Convert `NodeScriptParams.Tags` from `[]string` to `string` as the MAAS API v2 expect a single parameter for comma separated tags
- Convert `ApplyConfiguredNetworking`, `Destructive`, `MayReboot`, `Recommission` to `*bool` from `bool` with `omitempty`. By doing so, the users can either skip setting them and rely on script metadata, or setting them back to false during update.
Resolves: #135

fix: implement node script entities appropriately
